// Generated by scripts/fetch-bailian-models.mjs
// Source: https://dashscope.aliyuncs.com/api/v1/models?features=function-calling&capabilities=Reasoning&providers=qwen%2Czhipu-ai%2Cmini-max%2Cmoonshot-ai%2Cdeepseek&page_size=100&page_no=1
// Fetched: 2026-08-26T03:15:57.525Z

export type BailianModel = {
	id: string;
	name: string;
	reasoning: boolean;
	input: readonly ("text" | "image")[];
	cost: {
		input: number;
		output: number;
		cacheRead: number;
		cacheWrite: number;
		tiers?: readonly {
			input: number;
			output: number;
			cacheRead: number;
			cacheWrite: number;
			inputTokensAbove: number;
		}[];
	};
	contextWindow: number;
	maxTokens: number;
	compat: {
		supportsDeveloperRole: boolean;
		supportsReasoningEffort: boolean;
		maxTokensField: "max_tokens";
		requiresToolResultName: boolean;
		requiresMistralToolIds: boolean;
		thinkingFormat: "qwen";
	};
};

export const DEFAULT_COST = { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 };

export const QWEN_COMPAT = {
	supportsDeveloperRole: false,
	supportsReasoningEffort: false,
	maxTokensField: "max_tokens",
	requiresToolResultName: true,
	requiresMistralToolIds: true,
	thinkingFormat: "qwen",
} as const;

export const MODEL_CAPABILITIES: BailianModel[] = [
	{
		id: "deepseek-v4-flash",
		name: "DeepSeek-V4-Flash",
		reasoning: true,
		input: ["text"] as const,
		cost: { input: 1, output: 2, cacheRead: 0.2, cacheWrite: 0 },
		contextWindow: 1_000_000,
		maxTokens: 393_216,
		compat: QWEN_COMPAT,
	},
	{
		id: "deepseek-v4-flash-0731",
		name: "DeepSeek-V4-Flash-0731",
		reasoning: true,
		input: ["text"] as const,
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1_000_000,
		maxTokens: 393_216,
		compat: QWEN_COMPAT,
	},
	{
		id: "deepseek-v4-pro",
		name: "DeepSeek-V4-Pro",
		reasoning: true,
		input: ["text"] as const,
		cost: { input: 12, output: 24, cacheRead: 1, cacheWrite: 0 },
		contextWindow: 1_000_000,
		maxTokens: 393_216,
		compat: QWEN_COMPAT,
	},
	{
		id: "deepseek-v4-pro-0813",
		name: "DeepSeek-V4-Pro-0813",
		reasoning: true,
		input: ["text"] as const,
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 1_000_000,
		maxTokens: 393_216,
		compat: QWEN_COMPAT,
	},
	{
		id: "kimi-k3",
		name: "Kimi-K3",
		reasoning: true,
		input: ["image", "text"] as const,
		cost: { input: 20, output: 100, cacheRead: 2, cacheWrite: 0 },
		contextWindow: 1_048_576,
		maxTokens: 1_048_576,
		compat: QWEN_COMPAT,
	},
	{
		id: "kimi/kimi-k3",
		name: "kimi/kimi-k3",
		reasoning: true,
		input: ["text", "image"] as const,
		cost: { input: 20, output: 100, cacheRead: 2, cacheWrite: 0 },
		contextWindow: 1_048_576,
		maxTokens: 1_048_576,
		compat: QWEN_COMPAT,
	},
	{
		id: "MiniMax/MiniMax-M3",
		name: "MiniMax/MiniMax-M3",
		reasoning: true,
		input: ["image", "text"] as const,
		cost: { input: 4.2, output: 16.8, cacheRead: 0.84, cacheWrite: 0 },
		contextWindow: 1_048_576,
		maxTokens: 0,
		compat: QWEN_COMPAT,
	},
	{
		id: "qwen3.8-27b",
		name: "Qwen3.8-27B",
		reasoning: true,
		input: ["text", "image"] as const,
		cost: { input: 3, output: 12, cacheRead: 0.6, cacheWrite: 3.75 },
		contextWindow: 1_000_000,
		maxTokens: 131_072,
		compat: QWEN_COMPAT,
	},
	{
		id: "qwen3.8-max",
		name: "Qwen3.8-Max",
		reasoning: true,
		input: ["image", "text"] as const,
		cost: { input: 12, output: 36, cacheRead: 1.5, cacheWrite: 15 },
		contextWindow: 1_000_000,
		maxTokens: 131_072,
		compat: QWEN_COMPAT,
	},
	{
		id: "qwq-plus",
		name: "QwQ-Plus",
		reasoning: true,
		input: ["text"] as const,
		cost: { input: 1.6, output: 4, cacheRead: 0, cacheWrite: 0 },
		contextWindow: 131_072,
		maxTokens: 8_192,
		compat: QWEN_COMPAT,
	},
];
